### PR TITLE
feat: delay automatic trigger if there was running signals on `modulesLoaded`

### PR DESCRIPTION
**Pull request by Guria**

### CODE REVIEW

**Comment by Guria** [comment]
cc @christianalfoni

**Comment by christianalfoni** [comment]
Just to understand the change, in what scenario are signals running before the modules are loaded? The implementation looks good to me :-)

**Comment by Guria** [comment]
It can be auth* stuff, preparing some initial state that have to be loaded from server. It should be done whenever app loaded. I found, that triggering signal for this tasks from `componentDidMount` would happen even if `appMounted` signal was remembered with debugger. I have created [emulated scenario on todomvc app](https://github.com/cerebral/cerebral-todomvc/compare/delayed). It works perfectly in any combination of: with/without devtools remembering and/or router enabled/disabled.

Therefore we would recommend to do any initial signals running sync with `modulesLoaded` event. Router and devtools would just work transparent with this scenario without extra configuring.

**Comment by Guria** [comment]
@christianalfoni ready to merge. So are you ok with it?

**Comment by christianalfoni** [comment]
Okay, cool, I see! I am ok with it :-)

**Pull request merged**
