### PR TITLE
remove setting isSync flag for signals

### PR DESCRIPTION
**Pull request by Guria**
please try `npm i cerebral/cerebral-module-router#remove-isSync` on your projects and leave feedback here.
Known issue: debugger didn't show `routed` flag, but shows `frame`

### CODE REVIEW

**Comment by christianalfoni** [comment]
Yeah, debugger is due to logic I think. It only check routed if also signal is sync. Will test router soon

**Comment by christianalfoni** [comment]
Hm, I just get this: "cerebral-module-router@0.0.0-semantically-released  invalid".

**Comment by Guria** [comment]
@christianalfoni where you got it? did you ran `npm i cerebral/cerebral-module-router#remove-isSync`?

**Comment by Guria** [comment]
hmm, confirmed. looking what happened

**Comment by christianalfoni** [comment]
Yeah, damn npm3... it just states it being invalid. I can try mess around with it a bit more later

**Comment by Guria** [comment]
@christianalfoni don't sure why it states invalid, but it installs version from git anyway. so you can check it in fact

**Comment by christianalfoni** [comment]
Tested it on our project now. Seems to work just fine. Though I was a bit confused by the debugger. Gave both, `routed`, `frame` and `sync` on three different routes.

I believe the `routed` was indicated on initial routing (from url). Then `frame` was related to doing a router.redirect. And `sync` was related to running the signal as normal.

Does this make sense?

**Pull request merged**
