### PR TITLE
feat: create getter for current route

### PR DESCRIPTION
**Pull request by awei01**
I thought it might be useful to get this data directly from router module rather than trying to rebuild it.

### CODE REVIEW

**Comment by Guria** [comment]
@awei01 could you describe use case for this method?

**Comment by awei01** [comment]
Perhaps there is a more cerebral way to do this, but I'm trying to access the currently run signal in view layer (I'm using `cerebral-view-react). I'm trying to declaratively bind url routes to views (similar to `react-router`)

Another possible use case is to render a link that only handles/appends the query parameter.

**Comment by Guria** [comment]
Hm. First case looks interesting, but I feel not so good moving router declaration into view layer. `cerebral-module-router` designed to be optional, so `router` is just enables multiple entry points for application. Your case makes `router` be a source of state for component switcher.

Cerebral-way for doing this is using some component switcher #75 which is ruled by some state path + using `<Link>` component. This way your app can work in url-less environments without router at all. Then if you need router you can **declaratively bind url routes to _signals_**. Also you can easely use several nested component switchers, which will be hard with suggested syntax.

> `<Link signal={ currentRoute.match } params={ { modal: "sign_up" } }>Sign up now</Link>`

* Requires to extract controller from context to get router service
* uses internal implementation details (`url-mapper` api) which can be changed in future

Though, modal use-case looks like the case we should support, but I think it is a topic for separate discussion.

**Comment by awei01** [comment]
Ok, no problem. Good points.

**Pull request closed without merging**
